### ISSUE TITLE
different visual style for header keyword tables vs. data tables

### ISSUE THREAD

**Issue by sbailey** [desihub/desidatamodel#100]
Currently both header keyword tables and data tables use the same CSS styling.  If sphinx can support it, it would be UX helpful to have them visually distinguishable, e.g. with different background colors so that you can quickly tell when scrolling if you are looking at a data table or a header keyword table.

**Comment by weaverba137** [comment]
In principle I know how to do this, but there are finicky details in the needed CSS, because background color styling is applied at the cell (`<td>`) level rather than the row (`<tr>`) level.
