### ISSUE TITLE
Data model for calibration files in exposures and calibnight directories

### ISSUE THREAD

**Issue by weaverba137** [desihub/desidatamodel#108]
Please review the descriptions in the data model for these files:

* In `DESI_SPECTRO_REDUX/SPECPROD/exposures/NIGHT/EXPID`
  - cframe
  - exposure-qa
  - fiberflat
  - fiberflatexp
  - fit-psf
  - fit-psf-before-listed-fix
  - fit-psf-fixed-listed
  - fluxcalib
  - frame
  - psf
  - sframe
  - shifted-input-psf
  - sky
  - stdstars
* In `DESI_SPECTRO_REDUX/SPECPROD/preproc/NIGHT/EXPID`
  - preproc
* In `DESI_SPECTRO_REDUX/SPECPROD/calibnight/NIGHT`
  - biasnight
  - biasnighttest
  - fiberflatnight
  - psfnight

Note that Issue #106 concerns how to support the somewhat complex structure of the psfnight files in the `desidatamodel` automation, but is *not* related to the descriptions of HDUs, header keywords or columns within those files.

**Comment by julienguy** [comment]
Work in progress in branch calibration-files.

**Comment by weaverba137** [comment]
Closed by #127.
