### ISSUE TITLE
How to describe MTL files

### ISSUE THREAD

**Issue by forero** [desihub/desidatamodel#11]
@weaverba137 @sbailey I want to add a description of the MTL files generated by [this code in desitarget](https://github.com/desihub/desitarget/blob/master/py/desitarget/mtl.py#L7).

Is it enough to include a new ```mtl.rst``` file under ```doc/DESI_TARGET``` or is there anything else that should be done?

**Comment by weaverba137** [comment]
You would need to add a link to mtl.rst in doc/DESI_TARGET/index.rst.
