### ISSUE TITLE
Data model for qso afterburner files

### ISSUE THREAD

**Issue by weaverba137** [desihub/desidatamodel#110]
Please review the data model for the `qso_mgii` and `qso_qn` files in *both* healpix and tiles directories. The structural description of these files should be complete, but descriptions of the HDUs, header keywords and columns need work. If necessary it is possible for files to refer to other files, or for HDUs to refer to other HDUs, to reduce duplication of effort.

**Comment by echaussidon** [comment]
Hi @weaverba137, 

I commit the data model for the qso: https://github.com/desihub/desidatamodel/commit/c933d0b2e3a917d713bb0da8553836d2d4b2dbdb

I thought that I forked the package (I wanted to make a PR...). Sorry for that. 

Edmond

**Comment by weaverba137** [comment]
I'm not concerned about committing directly to `main`, however, it does make it much more difficult to comment on your changes, so please be sure to always create a branch and a PR in the future.

There is a serious issue with your changes: you have removed the optional marking from some columns, *i.e.*, `[1]_` and the corresponding `.. [1] Optional`.

The optional notation is needed by the automation that verifies that files obey the data model. For example, `SV1_DESI_TARGET` does not always appear in `qso_mgii` and `qso_qn` files, so it is marked as optional.

If you need to comment on columns, put the comments in the `Description` column. You can also put footnotes in the Description column, but footnotes in the `Name` column should only mark optional columns.

**Comment by weaverba137** [comment]
Please continue discussion on PR #134.  The changes that were originally on `main` are now on branch `qso-afterburner`.
