### ISSUE TITLE
Data model for guide-rois files

### ISSUE THREAD

**Issue by weaverba137** [desihub/desidatamodel#112]
Please review the data model for these files guide-rois files in `DESI_SPECTRO_DATA`

The structural description of this file should be complete, but descriptions of the HDUs, header keywords and columns need work. If necessary it is possible for files to refer to other files, or for HDUs to refer to other HDUs, to reduce duplication of effort.

@ameisner, I know we previously discussed assigning this to Santiago Serrano. Unfortunately, he was not very responsive, and may not even be affiliated with DESI any longer. If you can think of anyone else to assign this to, go ahead.

**Comment by ameisner** [comment]
Hi Ben,

I'm not sure about Santi, but I don't work for DESI anymore, although I do still use some of my personal research time to engage with the Legacy Surveys imaging team.

In the past, I got the sense that Connie and Klaus had good success at contacting Santi, so maybe you could try to get one of them involved. Other than Santi, Klaus might be the only person who really knows everything about the data model of these guider ROI files. I had the impression that David Kirkby made extensive use of these ROI files in various codes, so I'm pretty confident he (or one of his students?) knows a lot more about them than I do. Thanks...

-Aaron

**Comment by daqiii** [comment]
Santi is no longer working with DESI. He switched jobs some time ago.
Klaus

From: Aaron Meisner ***@***.***>
Date: Wednesday, June 8, 2022 at 5:22 AM
To: desihub/desidatamodel ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [desihub/desidatamodel] Data model for guide-rois files (Issue #112)
Hi Ben, I'm not sure about Santi, but I don't work for DESI anymore, although I do still use some of my personal research time to engage with the Legacy Surveys imaging team. In the past, I got the sense that Connie and Klaus had good success


Hi Ben,

I'm not sure about Santi, but I don't work for DESI anymore, although I do still use some of my personal research time to engage with the Legacy Surveys imaging team.

In the past, I got the sense that Connie and Klaus had good success at contacting Santi, so maybe you could try to get one of them involved. Other than Santi, Klaus might be the only person who really knows everything about the data model of these guider ROI files. I had the impression that David Kirkby made extensive use of these ROI files in various codes, so I'm pretty confident he (or one of his students?) knows a lot more about them than I do. Thanks...

-Aaron

**Comment by weaverba137** [comment]
Thank you @ameisner & @daqiii.  I will reassign to @dkirkby .

**Comment by weaverba137** [comment]
Indeed, those were previously updated by @ameisner, #96. So far, everyone who has been previously identified as having knowledge of these files has either left the DESI project or does not in fact have such knowledge. We really need some help here to find *someone* who can do this, so feel free to reassign.

**Comment by weaverba137** [comment]
Closed by #151.
