### ISSUE TITLE
Landing page for mask bits documentation

### ISSUE THREAD

**Issue by weaverba137** [desihub/desidatamodel#118]
We need a central "landing page" for documentation of all mask bits, analogous to [SDSS's bitmask page](https://www.sdss.org/dr17/algorithms/bitmasks/).

It is sufficient to *link* to mask bits documentation that is stored elsewhere.  For example, bits used by DECaLS can continue to be described on https://www.legacysurvey.org, but the new landing page should at least link to that documentation.

As a stretch goal, we could also describe other integers used in DESI, such as `TARGETID`, even though it is not technically a mask.

We are *not* advocating moving mask bits in *code* at this time. In other words, this issue is *not* intended to implement desihub/desiutil#113.

**Comment by julienguy** [comment]
Can @weaverba137 provide us with a placeholder file for the bitmask and an example for how link to it in the .rst files ?

**Comment by weaverba137** [comment]
Is the documentation here insufficient: https://desidatamodel.readthedocs.io/en/latest/datamodel.html

I think everyone would be much better served if I improved the documentation on that page so that you could provide this yourself.

Or am I missing something about the question?

**Comment by julienguy** [comment]
The documentation is good (I managed to cross-link the fibermap doc for instance). Could we have a placeholder page for bitmask in the repo so we can start writing correct links?

**Comment by weaverba137** [comment]
Glad the documentation is good.  You can start from this file: https://github.com/desihub/desidatamodel/blob/main/doc/bitmasks.rst.  Branch of off `main` to edit it.

**Comment by weaverba137** [comment]
This page was created by #139.
