### ISSUE TITLE
Data model for fvc and sky files in raw data

### ISSUE THREAD

**Issue by weaverba137** [desihub/desidatamodel#119]
Please review the data model for the fvc and sky files in `DESI_SPECTRO_DATA`.

The structural description of these files should be complete, but descriptions of the HDUs, header keywords and columns need work. If necessary it is possible for files to refer to other files, or for HDUs to refer to other HDUs, to reduce duplication of effort.

**Comment by weaverba137** [comment]
David Kirkby recommends contacting David Rabinowitz about this.  In addition to fvc files, we have also found `FVC-measure` and `fvc-primary` files in some early exposures that are in the raw data to be released.

**Comment by dkirkby** [comment]
Do we actually want to include FVC-measure and fvc-primary files in the
release, or is it too late to revisit that decision?

**Comment by weaverba137** [comment]
I would recommend asking that on the desi-data mailing list, but I think the general opinion would be that raw data are frozen once they come off the mountain, no matter what.

It would be reasonable to say "don't use these files" in the data model though.

**Comment by weaverba137** [comment]
Sky files have been addressed by #153.

**Comment by weaverba137** [comment]
Closed by #151.
