### ISSUE TITLE
Data model for ETC files in raw data

### ISSUE THREAD

**Issue by dkirkby** [desihub/desidatamodel#123]
The ETC json and jpg files are not yet mentioned in the top-level page and also need child pages.  I am assigning this to myself.

**Comment by weaverba137** [comment]
@dkirkby, thank you for taking this on. The data model automation is primarily focused on FITS files.  For non-FITS files, you should still include the title and the top-level summary: the part including the regular expression to match the file.  Otherwise the description can be more free-form than for files documenting FITS files.

**Comment by dkirkby** [comment]
@weaverba137 Here is the summary info for the ETC json files:

Summary: JSON file containing details of the ETC analysis for one DESI spectrograph exposure.
Naming Convention: ``etc-EXPID.json``, where EXPID is the zero-padded 8-digit exposure ID.
Regex: ``etc-[0-9]{8}\.json``
File Type: JSON, 0.1 Mb

Under "Contents" I suggest:

Each file contains a dictionary with the following top-level keys:
 - desietc: version number of the desietc package used.
 - expinfo: information about this spectrograph exposure including a summary of the results of analyzing the initial GFA acquisition images.
 - fassign: information about the fiber assignment for the tile to observe used by the ETC.
 - acquisition: details from the analysis of the initial in-focus GFA acquisition images.
 -guide_stars: details of the guide stars used from each in-focus GFA.
 - header: list of the ETC summary keywords that also appear in the main spectrograph FITS file.
 - shutter: tracking of successive cosmic-split exposures
 - thru: details of the per-GFA exposure analysis of fiber acceptance fraction and atmospheric transmission contributing to the signal throughput.
 - sky: details of the per-SKYCAM exposure analysis of relative sky background levels.
 - accum: details of the ETC model of accumulated of signal to noise after each GFA and SKYCAM exposure.

**Comment by weaverba137** [comment]
Thank you, I'll create a model file and test it.

**Comment by weaverba137** [comment]
Closed by #151.
