### ISSUE TITLE
maggies versus maggy in targeting files

### ISSUE THREAD

**Issue by weaverba137** [desihub/desidatamodel#129]
This issue first arose in #125. In some cases our commonly-used flux unit is variously spelled 'nanomaggie', 'nanomaggies' or 'nanomaggy'.

Going back to the original DR9 tractor files, 'nanomaggy' is used.  This seems to be retained in DESI targeting files derived from the tractor files.  However, this might not necessarily be the case further downstream.

As far as data model verification code goes, 'maggie', 'maggies' and 'maggy' are all acceptable.

For the purposes of this data model, let's make sure that the units in the model at least match the units in the actual file, and constrain the scope of this to files in the `DESI_TARGET` and `DESI_SURVEY` directories.

**Comment by geordie666** [comment]
Addressed in #133.
