### ISSUE TITLE
Script to sync column descriptions

### ISSUE THREAD

**Issue by weaverba137** [desihub/desidatamodel#137]
As part of @aureliocarnero's work on creating a central column definition list, once that work is done, we should create a script that will sync *existing* files with that list, with options to simply point out differences or to actually make changes to the files.

**Comment by weaverba137** [comment]
@aureliocarnero, could you give an update on your work to create a central column definition list?

**Comment by ashleyjross** [comment]
(Aurelio is on paternity leave until the end of January.)

**Comment by weaverba137** [comment]
@aureliocarnero, this is very good to hear! We have a documentation sprint going on and there are other people interested in this same goal. This is a great start.

**Comment by weaverba137** [comment]
Here is a [useful list of units](https://github.com/desihub/desitarget/blob/main/py/desitarget/data/units.yaml) used by desitarget that could be used as a starting point.

**Comment by geordie666** [comment]
With the caveat that some of those units don't conform to the FITS standard. See the [notes at the bottom of, e.g., this page](https://desidatamodel.readthedocs.io/en/latest/DESI_TARGET/TARG_DIR/DR/VERSION/targets/PHASE/RESOLVE/OBSCON/PHASEtargets-OBSCON-RESOLVE-hp-HP.html) which also contains a useful snippet of code for determining the FITS-compliant unit.

**Comment by weaverba137** [comment]
Yes, we did mention that to the people interested in this.

**Comment by weaverba137** [comment]
@sbailey has been working on some code related to this, so reassigning.

**Comment by weaverba137** [comment]
Closing because this script now exists as of #144.
