### ISSUE TITLE
Boolean types in column descriptions file

### ISSUE THREAD

**Issue by weaverba137** [desihub/desidatamodel#148]
There are several columns in `column_descriptions.csv` that are Boolean (`bool`) type, but `IS_QSO_MGII` is marked as `logical`. This should probably just be changed to `bool`.  However, there are some other examples where the type is unclear, for example, Lines 159-160, with descriptions "LOCATION_ASSIGNED described as 0/1" and "LOCFULL described as True/False". These lines have no type.

**Comment by ashleyjross** [comment]
LOCATION_ASSIGNED should be bool

LOCFULL is another one to scrub from our files (if it remains in any; it is not used for anything in the end)

**Comment by aureliocarnero** [comment]
Please see pull request solving this issue:
https://github.com/desihub/desidatamodel/pull/149

**Comment by weaverba137** [comment]
Closed by #149.
