### ISSUE TITLE
cleanup default datamodel descriptions

### ISSUE THREAD

**Issue by sbailey** [desihub/desidatamodel#163]
grep datamodel files for placeholders:
  * "Brief Description"
  * "label for field"
  * "Add notes and examples here"
  * "TODO"
  * "Summarize the contents of this HDU"

Cleanup as many of those as possible prior to EDR.  "label for field" ones can generally be handled by running `update_column_descriptions` on the file.

**Comment by weaverba137** [comment]
@sbailey, here's a preliminary analysis of placeholder descriptions:

* "Brief Description" / "Summarize the contents of this HDU.": there aren't a lot of these, but `update_column_descriptions` won't help with this. What is the best way to proceed with filling these in?
* "label for field": A lot of these are in `DESI_SPECTRO_DATA`. I'm not sure how much `update_column_descriptions` will help with these.  The really shocking thing here is that some columns in the zcatalog directory still have that issue.  I thought all of those were 100% fixed in a recent PR.
* "Add notes and examples here": I propose removing the entire Examples section if that is its only content.
* "TODO": These are extremely rare.  I can just list all of the appearances:
  * `doc/DESI_SPECTRO_DATA/NIGHT/EXPID/fibermap-EXPID.rst`: TODO: standardize keywords with ICS, *e.g.* ``FLAVOR -> PROGRAM``.
  * `doc/DESIMODEL/data/throughput/DESI-0347.rst`: TODO: expand description with links to documentation about how this is used.
  * `doc/DESI_SPECTRO_SIM/PIXPROD/NIGHT/EXPID/pix-CAMERA-EXPID.rst`: VSPECTER 0.0.0         str   TODO: Specter version
  * `doc/DESI_SPECTRO_SIM/PIXPROD/NIGHT/EXPID/simspec-EXPID.rst`: TODO: define if AIRMASS etc. are at middle of exposure, averaged, etc.
  * `doc/DESI_SPECTRO_REDUX/SPECPROD/exposures/NIGHT/EXPID/stdstars-SPECTROGRAPH-EXPID.rst`: TODO: add example of what that means.

**Comment by weaverba137** [comment]
@sbailey some additional data points and updates.

I've already removed all of the empty `Notes and Examples` sections.

Most of the remaining placeholder descriptions are in two areas: `DESI_SPECTRO_DATA`, although I'm making progress there, and `DESI_ROOT/survey/fiberassign/SURVEY/TILEXX`, *i.e.* the intermediate fiberassign files.  In the latter case, it looks like the placeholder files were generated, and then no one ever added any information at all to them.  I can probably fill in many of the column descriptions, but I have no information on the overall purpose of each file or each HDU within a file.

Other isolated cases (duplicate issues within the same file have been removed):
```
doc/DESI_SPECTRO_REDUX/SPECPROD/exposures/NIGHT/EXPID/fluxcalib-CAMERA-EXPID.rst:HDU4_  FIBERCORR        BINTABLE *Brief Description*
doc/DESI_SPECTRO_REDUX/SPECPROD/exposures/NIGHT/EXPID/fiberflatexp-CAMERA-EXPID.rst:HDU0_  FIBERFLAT  IMAGE    *Brief Description*
doc/DESI_SPECTRO_REDUX/SPECPROD/exposures/NIGHT/EXPID/stdstars-SPECTROGRAPH-EXPID.rst:HDU5_  FIBERMAP     BINTABLE *Brief Description*
doc/DESI_SPECTRO_REDUX/SPECPROD/exposures/NIGHT/EXPID/stdstars-SPECTROGRAPH-EXPID.rst:*Summarize the contents of this HDU.*
doc/DESI_SPECTRO_REDUX/SPECPROD/exposures/NIGHT/EXPID/stdstars-SPECTROGRAPH-EXPID.rst:TODO: add example of what that means.
doc/DESI_SPECTRO_REDUX/SPECPROD/calibnight/NIGHT/psfnight-CAMERA-NIGHT.rst:PARAM   char[8]             label for field   1
doc/DESIMODEL/data/throughput/DESI-0347.rst:TODO: expand description with links to documentation about how this is used.
doc/DESI_SPECTRO_SIM/PIXPROD/NIGHT/EXPID/pix-CAMERA-EXPID.rst:VSPECTER 0.0.0         str   TODO: Specter version
doc/DESI_SPECTRO_SIM/PIXPROD/NIGHT/EXPID/simspec-EXPID.rst:TODO: define if AIRMASS etc. are at middle of exposure, averaged, etc.
```
The `stdstars` file really needs some attention!

For reference, these will find the placeholder cases if run in a checkout of desidatamodel:

* Missing top-level description: `grep -r -i 'high-level' doc`.
* Missing HDU summary description: `grep -r -i 'brief description' doc`.
* Missing HDU detail description: `grep -r -i 'summarize' doc`.
* Placeholder column description: `grep -r -i 'label for' doc`.
* Empty notes: `grep -r -i 'Add notes' doc`.
* TODO: `grep -E -r -i 'to ?do' doc`.

**Comment by weaverba137** [comment]
Also these files appear to have *blank* column descriptions, as opposed to `label for field` placeholders:
```
doc/DESI_SPECTRO_REDUX/SPECPROD/preproc/NIGHT/EXPID/preproc-CAMERA-EXPID.rst
doc/DESI_SPECTRO_REDUX/SPECPROD/exposures/NIGHT/EXPID/stdstars-SPECTROGRAPH-EXPID.rst
doc/DESI_SPECTRO_REDUX/SPECPROD/exposures/NIGHT/EXPID/fiberflatexp-CAMERA-EXPID.rst
doc/DESI_SPECTRO_REDUX/SPECPROD/exposures/NIGHT/EXPID/fluxcalib-CAMERA-EXPID.rst
doc/DESI_SPECTRO_SIM/PIXPROD/NIGHT/EXPID/simspec-EXPID.rst
doc/DESIMODEL/data/focalplane/fiberpos.rst
doc/DESIMODEL/data/focalplane/fiberpos-all.rst:
```
For reference, those were found with:
```
grep -E -r '^[^ .=]+ +[^ ]+ +[^ ]*$' doc | \
    grep -v 'Required Header Keywords' | \
    grep -v 'EXTNAME =' | \
    grep -v 'Notes and Examples' | \
    grep -v 'FITS Header Units' | \
    grep -v 'imperfect sky subtraction' | \
    grep -v index.rst | \
    grep -v conf.py | \
    grep -v HDU0_
```
and even then there is still a fair bit to sift through.

**Comment by weaverba137** [comment]
@araichoor, I've filled in the column definitions in the intermediate fiberassign files. However, a handful of columns do not appear in the master CSV file (note that there are some duplicates):
```
TILEID-scnd.rst:PLATE_REF_EPOCH       float32            label for field  36
TILEID-sky.rst:BLOBDIST         float32 pix          label for field   7
TILEID-sky.rst:FIBERFLUX_IVAR_G float32 nanomaggy^-2 label for field  11
TILEID-sky.rst:FIBERFLUX_IVAR_R float32 nanomaggy^-2 label for field  12
TILEID-sky.rst:FIBERFLUX_IVAR_Z float32 nanomaggy^-2 label for field  13
TILEID-targ.rst:PLATE_REF_EPOCH       float32               label for field  63
TILEID-tiles.rst:IN_DESI       int16         label for field   5
TILEID-too.rst:SCND_ORDER                    int32              label for field  17
TILEID-too.rst:CHECKER                       char[5]            label for field  22
TILEID-too.rst:TOO_TYPE                      char[5]            label for field  23
TILEID-too.rst:TOO_PRIO                      char[2]            label for field  24
TILEID-too.rst:OCLAYER                       char[6]            label for field  25
TILEID-too.rst:MJD_BEGIN                     float64  d         label for field  26
TILEID-too.rst:MJD_END                       float64  d         label for field  27
TILEID-too.rst:TOOID                         int64              label for field  28
TILEID-too.rst:PLATE_REF_EPOCH               float64            label for field  32
```
Could you please fill those in and add them to the CSV file? Or just let me know what those should be?

**Comment by araichoor** [comment]
hi @weaverba137,

thanks a lot.
please find below the infos for the columns you mention.

- `PLATE_REF_EPOCH`: this is a copy of the `REF_EPOCH` column (coupled with `PLATE_{RA,DEC}` being a copy a `TARGET_{RA,DEC}`);
- `TILEID-sky.rst` columns:
    - see https://github.com/desihub/desidatamodel/blob/main/doc/DESI_TARGET/TARG_DIR/DR/VERSION/skies/skies-hp-HP.rst; 
 - `TILEID-tiles.rst:IN_DESI`: 0 or 1; always set to 1, so that fiberassign "accepts" to design the tile (otherwise the default onlydesi=True option in desimodel.io.load_tiles() discards tiles outside the desi footprint);
 - `TILEID-too.rst`: see https://github.com/desihub/desidatamodel/blob/main/doc/DESI_SURVEYOPS/mtl/sv3/ToO/ToO.rst

also a few of remarks on https://github.com/desihub/desidatamodel/pull/167/files/2ec912ca1c3500d179e2a4b23f7d65ee826c39c5..195bbff51c48a1b969d93ee86cf850d8f5d1ea2b#diff-4651697587639c37d25ccd237a871af2560168291dd68e1934891de8b47375ae:
- `TILEID-sky.rst`:
    -  see https://github.com/desihub/desidatamodel/blob/main/doc/DESI_TARGET/TARG_DIR/DR/VERSION/skies/skies-hp-HP.rst;
    - note that for the skies, the `FIBERFLUX_{GRZ}` is not as for the targets, ie it s not the tractor model convolved with some seeing and cut on the fiber size; it s actually some aperture magnitude measurement; see `skies-hp-HP.rst`;
- `TILEID-tiles.rst`:
    -  `RA`, `DEC`: maybe precise `Tile Right Ascension` and `Tile Declination` ?
    - `PROGRAM`: actually it s the survey (CMX, SV1, SV2, SV3)... life would be otherwise too simple... I m not really sure that this column is used downstream.

**Comment by weaverba137** [comment]
Thank you! I'll put those together shortly.  That just leaves the top-level and HDU descriptions, for example in [TILEID-gfa](https://desidatamodel.readthedocs.io/en/latest/DESI_ROOT/survey/fiberassign/SURVEY/TILEXX/TILEID-gfa.html), the top-level description is "This section should be filled in with a high-level description of this file."

**Comment by araichoor** [comment]
please find below my suggestion for the top-level and hdu descriptions.
and let me know if I shall provide those to you in a different way..

First for the tileid (`TILEID-tiles.rst`):
- top-level: This file contains the designed properties of the observed tile.
- hdu1 brief descr.: Tile designed properties.
- hdu1 full descr.: Tile designed properties.

Then for the other ones:
- top-level: This file contains the XXX covered by the tile disk-footprint.
- hdu1 brief descr.: XXX covered by the tile disk-footprint.
- hdu1 full descr.: XXX covered by the tile disk-footprint: those are read from the YYY catalogs and provided as input to fiberassign.

with:
- `TILEID-scnd.rst`: XXX="Secondary targets", YYY="MTL ledgers and desitarget"
- `TILEID-gfa.rst`: XXX="Star for the ETC / GUIDE / FOCUS", YYY="desitarget"
- `TILEID-sky.rst`: XXX="Sky targets", YYY="desitarget"
- `TILEID-targ.rst`: XXX="Primary science targets", YYY="MTL ledgers and desitarget"
- `TILEID-too.rst`: XXX="Target-of-Opportunity targets", YYY="MTL ledgers and desitarget"

**Comment by weaverba137** [comment]
I think that will be fine thank you!

**Comment by araichoor** [comment]
great.

also I remark that there is no `TILEID-std.rst`: I did generate those files for SV1.
it was just that I kept in a separate file the standard stars (as I was not sure in the beginning if fiberassign needs a separate file or not).

in case you add a `TILEID-std.rst`, it would be the same as the ones above, with:
- XXX="Standard stars" and YYY="desitarget".

**Comment by araichoor** [comment]
btw, I notice that here, there s a `EXPID`, which should be `TILEID`: https://github.com/desihub/desidatamodel/blob/edr-cleanup/doc/DESI_TARGET/fiberassign/tiles/TILES_VERSION/TILEXX/fiberassign-TILEID.rst#fiberassign-expid
I guess it s a leftover from the original rst files.

**Comment by weaverba137** [comment]
Good catch, I will fix that as well.

**Comment by araichoor** [comment]
and a minor comment for `PLATE_REF_EPOCH`: with seeing how `PLATE_{RA,DEC}` are described, it looks like it should be phrased as "REF_EPOCH to be used by PlateMaker"; sorry that I ve missed that.

**Comment by araichoor** [comment]
last remark: except for the tiles file, I see this "required header keywords", e.g.: https://github.com/desihub/desidatamodel/blob/edr-cleanup/doc/DESI_ROOT/survey/fiberassign/SURVEY/TILEXX/TILEID-gfa.rst#required-header-keywords

I don t know if those should be filled in or not (see below).
my understanding is that those are created by the desitarget routines that I used to write the files.
so those should have the same meaning as in the "corresponding" desitarget file e.g. for the `targ`: https://github.com/desihub/desidatamodel/blob/edr-cleanup/doc/DESI_TARGET/TARG_DIR/DR/VERSION/targets/PHASE/RESOLVE/OBSCON/PHASEtargets-OBSCON-RESOLVE-hp-HP.rst#required-header-keywords

though, I m not sure if the values are all correctly filled, I ve never checked those.
spot-checking few files, they make sense (though some can be empty).
hopefully those are propagated from the reading of the desitarget catalogs.

**Comment by weaverba137** [comment]
Those keywords would have been generated from an example of the same type of file. Unless the set of keywords has changed radically over the years, they should be OK.

Coming back to the description of `FIBERFLUX_(G|R|Z)`, is `AP0` propagated into these files? From [the example you provided](https://github.com/desihub/desidatamodel/blob/main/doc/DESI_TARGET/TARG_DIR/DR/VERSION/skies/skies-hp-HP.rst), it appears that `AP0` has a value of 0.75, which means that the diameter really is 1.5 arcsec: "Predicted g-band flux within a fiber of diameter 1.5 arcsec from this object in 1 arcsec Gaussian seeing". Is it the seeing that is not applied?

**Comment by geordie666** [comment]
Note that the description of `FIBERFLUX_(G|R|Z)` for the [desitarget skies files](https://github.com/desihub/desidatamodel/blob/edr-cleanup/doc/DESI_TARGET/TARG_DIR/DR/VERSION/skies/skies-hp-HP.rst) is "g-band object model flux calculated in aperture of radius AP0" so no seeing is implied (or included). 

It is unfortunate that those quantities have [the same name as for sources from the Legacy Surveys ](https://www.legacysurvey.org/dr10/files/#sweep-brickmin-brickmax-fits).

**Comment by weaverba137** [comment]
OK, But is `AP0` always 0.75? If not, is the value of `AP0` propagated forward into the intermediate fiberassign files?

**Comment by araichoor** [comment]
fiberassign is unaware of that `AP0` parameter; and from checking 1-2 TILEID-sky.fits files, it s not propagated in the header.

it s just that those `FIBERFLUX` values are propagated from the desitarget catalogs into those intermediate fiberassign files, and downstream.

I suspect that, yes, `AP0` always is 0.75, as we re looking for the flux in a desi fiber; again @geordie666 can confirm that.
(that should be the `aperture_arcsec` argument here: https://github.com/desihub/desitarget/blob/0e0145f03597fe0b597db85027d2a7d46bba1fd6/py/desitarget/skyfibers.py#L174-L175)

**Comment by geordie666** [comment]
I believe that every `desitarget` skies file was run with `AP0=0.75`. I can quickly spool through the files and check.

To Anand's other point about whether seeing is included or not, `desitarget` directly force-photometers  the Legacy Surveys coadd `image` stacks to retrieve these quantities (using an aperture of radius 0.75"). From the [Legacy Surveys documentation](https://www.legacysurvey.org/dr10/files/#image-stacks-south-coadd):
```
<AAA>/<brick>/legacysurvey-<brick>-image-<filter>.fits.fz

    Stacked image centered on a brick location covering 0.25° × 0.25°. The primary HDU contains the coadded image (inverse-variance weighted coadd), in units of nanomaggies per pixel.

        NOTE: These are not the images used by Tractor, which operates on the single-epoch images.

        NOTE: These images are resampled using Lanczos-3 resampling.

        NOTE: Images in WISE bands are on the Vega system, all other flux-related quantities in DR10 are reported on the AB system. The [description](https://www.legacysurvey.org/dr10/description/#photometry) page lists the Vega-to-AB conversions [recommended by the WISE team](http://wise2.ipac.caltech.edu/docs/release/allsky/expsup/sec4_4h.html#conv2ab).
```
I'm not sure, actually, whether the seeing is resampled to a fixed scale in those images (or removed), or whether the seeing is a combination of whatever the "true" seeing was across the stacked images. I think we'd have to ask Dustin if we deeply cared.

**Comment by weaverba137** [comment]
For the purposes of this one set of column descriptions, I think we can say:

"g-band object flux measured in aperture of radius AP0, usually 0.75 arcsec, with no seeing correction"

Does that sound OK?

**Comment by moustakas** [comment]
> I'm not sure, actually, whether the seeing is resampled to a fixed scale in those images (or removed), or whether the seeing is a combination of whatever the "true" seeing was across the stacked images. I think we'd have to ask Dustin if we deeply cared.

The coadds are just an ivar-weighted stack of the input pixels, resampled to the brick tangent plane and 0.262 pixel scale, with no seeing homogenization of the input data.

**Comment by geordie666** [comment]
Confirming that we _did_ always use `AP0=0.75`:
```
from glob import glob
import fitsio
fns = sorted(glob("/global/cfs/cdirs/desi/target/catalogs/dr9/*/skies/skies-hp-0.fits"))
for fn in fns:
    a = fitsio.read_header(fn, 1)
    print(fn, a["AP0"])
   ...: 
/global/cfs/cdirs/desi/target/catalogs/dr9/0.47.0/skies/skies-hp-0.fits 0.75
/global/cfs/cdirs/desi/target/catalogs/dr9/0.48.0/skies/skies-hp-0.fits 0.75
/global/cfs/cdirs/desi/target/catalogs/dr9/0.49.0/skies/skies-hp-0.fits 0.75
/global/cfs/cdirs/desi/target/catalogs/dr9/0.50.0/skies/skies-hp-0.fits 0.75
/global/cfs/cdirs/desi/target/catalogs/dr9/0.51.0/skies/skies-hp-0.fits 0.75
/global/cfs/cdirs/desi/target/catalogs/dr9/0.52.0/skies/skies-hp-0.fits 0.75
/global/cfs/cdirs/desi/target/catalogs/dr9/0.57.0/skies/skies-hp-0.fits 0.75
/global/cfs/cdirs/desi/target/catalogs/dr9/0.58.0/skies/skies-hp-0.fits 0.75
/global/cfs/cdirs/desi/target/catalogs/dr9/1.0.0/skies/skies-hp-0.fits 0.75
/global/cfs/cdirs/desi/target/catalogs/dr9/1.1.0/skies/skies-hp-0.fits 0.75
/global/cfs/cdirs/desi/target/catalogs/dr9/1.1.1/skies/skies-hp-0.fits 0.75
/global/cfs/cdirs/desi/target/catalogs/dr9/2.2.0/skies/skies-hp-0.fits 0.75
```
