### ISSUE TITLE
DESINAME needs an entry in column descriptions

### ISSUE THREAD

**Issue by weaverba137** [desihub/desidatamodel#188]
We're going to add `DESINAME` to fibermap and downstream files soon (see desihub/desispec#2149). As I was doing this, I noticed there is no formal column description for `DESINAME` in desidatamodel. I could not find a string length either. If this is known already, it's easier to ask.

**Comment by weaverba137** [comment]
I think DESINAME is 22 characters, but it would be good to confirm that.

**Comment by akremin** [comment]
Yes `DESINAME` should always be 22 characters, e.g. "DESI J094.5633+50.3052".

My one-minute pass at a column description, which is likely too long to be implemented as-is:
"Identifier of a sky location precise to ~0.36 arcseconds that generally be used to refer to an object in a human-readable way. Note multiple objects can map to a single DESINAME if very close on the sky."
