### ISSUE TITLE
PROTODESI_DATA files

### ISSUE THREAD

**Issue by weaverba137** [desihub/desidatamodel#19]
I noticed a few problems with the PROTODESI_DATA files that should be addressed before that branch is merged.

1. The naming conventions for the various files has a three-digit exposure ID and a 5-digit MJD.  Are we absolutely certain that protoDESI will never produce more than 999 exposures, or is the exposure ID reset every day (which seems dangerous)?  Also, the rest of the pipeline is using eight-digit YYYYMMDD instead of MJD.  Is it possible to use YYYYMMDD for consistency?
2. The main DESI pipeline has largely abandoned mixed-case filenames in favor of all lowercase.  
3. The files describe FITS files that have binary tables in HDU0, which is not allowed.  It appears there is some confusion about the difference between Header Keywords and Column Names.
4. The index.rst file has incorrect links in the `toctree` section.  The links should simply be *e.g.* `pdFVC` not `pdFVC/index`.

**Comment by weaverba137** [comment]
@sbailey, please note this desidatamodel issue related to recent discussions on desi-data about MJD.

**Comment by weaverba137** [comment]
Is anyone working on the protoDESI data model, since we could be getting data literally any day now?

**Comment by givoltage** [comment]
1&2. The naming conventions are as follows (as of now)
> PROTODESI_FPC_00000050.rst
> PROTODESI_GFA0_00001000_0000.fits
> PROTODESI_FPCS_00000927.fits
If data pipeline requires that date be in the filename or be all lowercase, I'll check with Parker and Klaus.

3. HDU0 contains raw float16 image. The bintable was probably just an example value that was put there.
4. Fixed.

**Comment by weaverba137** [comment]
OK, I think we can close this.
