### ISSUE TITLE
Units of SKY_MAG_X_SPEC and SKY_MAG_AB_GFA

### ISSUE THREAD

**Issue by rongpu** [desihub/desidatamodel#190]
https://desidatamodel.readthedocs.io/en/latest/DESI_SPECTRO_REDUX/SPECPROD/exposures-SPECPROD.html

SKY_MAG_G_SPEC is described as "Sky background measured in the spectroscopy integrated over the DECam g passband, AB mags", but is it mag / arcsec^2, or is it the total sky flux measured by the fiber?

SKY_MAG_AB_GFA has no units.

**Comment by weaverba137** [comment]
@sbailey could you take a quick look at this? Who is likely to be the expert on this?

**Comment by sbailey** [comment]
`SKY_MAG_*_SPEC` is computed in https://github.com/desihub/desispec/blob/main/py/desispec/skymag.py#L47 which says "AB magnitudes per arcsec2" and I confirmed in the code that it is dividing by the mean fiber area (but not the individual fiber areas of the sky fibers).

I'm assuming that `SKY_MAG_AB_GFA` has the same units, but I'm not actually sure where that comes from other than guessing that it comes from the gfa pipeline.

**Comment by araichoor** [comment]
for the `SKY_MAG_AB_GFA`, one could dive into the code, but from some early SV1 documentation, it should also be "AB mag/arcsec2": https://desi.lbl.gov/trac/wiki/SurveyValidation/SV1/conditions/summary_files#ex3.
