### ISSUE TITLE
Review datamodel for 17.12 consistency

### ISSUE THREAD

**Issue by sbailey** [desihub/desidatamodel#40]
Update datamodel as needed to match the results of software release 17.12 in /project/projectdirs/desi/datachallenge/reference_runs/17.12 .

In some cases where they differ, the datamodel may reflect what we really want.  Make sure that the datamodel is clear that this isn't yet implemented, and make sure that there is a ticket for getting the code to implement the desired datamodel.

**Comment by weaverba137** [comment]
Closing.  Make further comments on #42.
