### ISSUE TITLE
Can we remove "brick" models?

### ISSUE THREAD

**Issue by weaverba137** [desihub/desidatamodel#43]
There are still references to brick-based reduction files, especially in the `DESI_SPECTRO_REDUX` section.  Can these be removed?  In general, what brick-based models need to be retained, and what can be removed?

**Comment by sbailey** [comment]
Yes, brick-based reduction files can be removed from the desidatamodel.  Please close this ticket when that is done.

**Comment by weaverba137** [comment]
The brick-based files have been removed from `DESI_SPECTRO_REDUX`. I couldn't find other obvious brick-based files in other sections.  This will be implemented when #42 is merged.
