### ISSUE TITLE
How do data models in DESI_TARGET map to files in reference runs?

### ISSUE THREAD

**Issue by weaverba137** [desihub/desidatamodel#44]
The data model files in the `DESI_SPECTRO_(DATA|REDUX|SIM)` sections map cleanly onto directories in the recent reference runs.  However, data model files in the `DESI_TARGET` section do not.  This includes fiber assignment files.

**Comment by sbailey** [comment]
Starting from a reference run base directory:

Reference Run | Data Model
---------------|-------------
targets/targets.fits | $DESI_TARGET/targets-{source}-{version}.fits
targets/mtl.fits | $DESI_TARGET/mtl-{source}-{version}.fits
targets/truth.fits | $DESI_TARGET/truth-{source}-{version}.fits
targets/sky.fits | $DESI_TARGET/sky-{version}.fits
targets/standards-dark.fits | $DESI_TARGET/stdstar-{version}.fits
targets/standards-bright.fits | $DESI_TARGET/stdstar-{version}.fits
fiberassign/tile_*.fits | $DESI_TARGET/fiberassign/tile_*.fits

Note: reference runs currently have two different standards files for dark vs. bright, while long term we may only have 1.

Not yet in the datamodel, but will apply to real data too:
* targets/qa/

Specific to reference runs with no equivalent in the datamodel:
  * targets/test-tiles.fits
  * targets/select_mock_targets.log
  * targets/{group}/{pixnum}/*.*
  * fiberassign/*.txt, *.log

**Suggestion**: for the files that do have an equivalent, update the data model as needed to document the *contents* of the existing files, but don't worry about directory structure or file names yet.  I don't think the reference run or the data model reflect what we really want but I don't have an organized suggestion of what to do yet.

**Comment by weaverba137** [comment]
OK, this sounds reasonable.

**Comment by weaverba137** [comment]
I have updated the data model files to reflect the reference run versions of the targets and fiberassign files.  The changes are part of #42.
