### ISSUE TITLE
list of scalars being tested 

### ISSUE THREAD

**Issue by felipeaoli** [desihub/desidatamodel#49]
In desidatamodel/doc/QUICKLOOK/*.rst, we need the information of which scalar is being tested in *_NORMAL_RANGE and *_WARN_RANGE when the *_STATUS is created. This info was available in older versions of datamodel.

**Comment by rkehoe** [comment]
The scalar metrics are included in each .rst file, either for individual QAs or for the mergedQA file.  The naming convention is for the scalar metric naming, minus the granularity part (eg. _AMP or _TGT) is then appended with the _STATUS key for the final assessment based on the _RANGE specifications.  So NOISE_AMP yields NOISE_STATUS.  It may be worth saying this in the .rst files explicitly as naming conventions are appropriate to include there.  To summarize what is current, QL currently has the following scalar metric list for each QA:

"Check_HDUs":"HDUs_OK",
"Trace_Shifts":"TRACE_REF",
"Bias_From_Overscan":"BIAS_AMP",
"Get_RMS":"NOISE_AMP", 
"Count_Pixels":"LITFRAC_AMP",
"Calc_XWSigma":"XWSIGMA",
"CountSpectralBins":"NGOODFIB", 
"Sky_Peaks":"PEAKCOUNT", 
"Sky_Continuum":"SKYCONT", 
"Integrate_Spec":"DELTAMAG_TGT", 
"Sky_Residual":"MED_RESID", 
"Calculate_SNR":"FIDSNR_TGT"}

The default right now is for flexure to be turned off, so TRACE would not be included in your outputs.  And you may also have Sky_Residual turned off.

**Comment by weaverba137** [comment]
@rkehoe, is this still an open issue?
