### ISSUE TITLE
Update fiberassign tile file data model

### ISSUE THREAD

**Issue by weaverba137** [desihub/desidatamodel#51]
The data model for the fiberassign tile files has changed and needs to be updated for release 18.6.  See also desihub/desitest#12.

**Comment by sbailey** [comment]
I'll take care of this, along with updating for the new NIGHT/EXPID/ raw data subdirectories.

**Comment by forero** [comment]
Thanks!

**Comment by sbailey** [comment]
fixed by PR #52
