### ISSUE TITLE
'electron' is not a valid unit in the FITS standard

### ISSUE THREAD

**Issue by weaverba137** [desihub/desidatamodel#53]
I'm trying to make sure that all units defined in FITS files (`BUNIT` and `TUNIT` keywords) conform to the FITS standard.  Unfortunately 'electron' is not valid.  

See `doc/DESI_SPECTRO_REDUX/SPECPROD/exposures/NIGHT/EXPID/calib-CAMERA-EXPID.rst` for an example.  Would `adu` be an acceptable substitute?

**Comment by sbailey** [comment]
ADU are the raw detector counts, while electrons are the gain-corrected ADUs (as extracted into spectra in this case).  `count` would be better (and is an allowed unit).

**Comment by weaverba137** [comment]
Yes, `count` works fine.

Another: `Angstrom/row` in `doc/DESIMODEL/data/specpsf/psf-quicksim.rst`.  `Angstrom/pixel` would work.

**Comment by sbailey** [comment]
I have a minor preference for Angstrom/bin.  bin=1D, pixel=2D, voxel=3D, though I recognize that many people also use pixel for 1D.  The [FITS standard](https://fits.gsfc.nasa.gov/standard40/fits_standard40aa.pdf) table 4 describes "bin" as "numerous applications (including the 1-d analogue of pixel)".

**Comment by weaverba137** [comment]
`bin` sounds fine to me.
