### ISSUE TITLE
don't rely on docDB to document fiberassign data model

### ISSUE THREAD

**Issue by moustakas** [desihub/desidatamodel#56]
In order to properly interpret the fiberassign HDUs --
  https://desidatamodel.readthedocs.io/en/latest/DESI_TARGET/fiberassign/tile.html
one has to read [DESI-0530](https://desi.lbl.gov/DocDB/cgi-bin/private/ShowDocument?docid=530) and [DESI-1049](https://desi.lbl.gov/DocDB/cgi-bin/private/RetrieveFile?docid=1049;filename=fiber_format.pdf;version=3) on DocDB.

It would be nice to have the "essential" information self-contained in the `desidatamodel` page, especially for the `POTENTIAL` HDU, which is a fairly short and straightforward.

Also: note that the extension name has changed: `POTENTIAL_ASSIGNMENTS` --> `POTENTIAL`

**Comment by sbailey** [comment]
+1 for the datamodel to be sufficient for interpreting the basic data format.  Also see new ticket desihub/fiberassign#138 for discussion about exactly which columns should be included in this HDU to make it more user friendly.

**Comment by sbailey** [comment]
fiberassign now writes out a more user friendly potential assignments table that doesn't rely upon reading DocDB to know how to unpack it.  Closing.
