### ISSUE TITLE
add desimodel files to datamodel

### ISSUE THREAD

**Issue by sbailey** [desihub/desidatamodel#6]
The desimodel files are lightly documented in the [desimodel/doc](https://desi.lbl.gov/trac/browser/code/desimodel/trunk/doc) directory and in [DESI-0847](https://desi.lbl.gov/DocDB/cgi-bin/private/ShowDocument?docid=874), but we should add more detailed data model documentation to desidatamodel.  This would be a new top-level DESIMODEL directory, at the same level as DESI_SPECTRO_REDUX, etc.

**Comment by weaverba137** [comment]
In light of #7, we should really get these data models written.

**Comment by weaverba137** [comment]
The structure exists for this now, but no actual content has been added yet.

**Comment by weaverba137** [comment]
To support the 2017 Data Challenge, I'd like to get this done.

**Comment by weaverba137** [comment]
I'm starting to add files on the `desimodel-update` branch.  Feel free to take a look at those and edit as needed.

**Comment by weaverba137** [comment]
At this point, I've added files that describe all areas of the desimodel data directory, *except* the spectra directory.  While examining that directory, a few other questions came up that need to be answered before I can proceed (see desihub/desimodel#47, desihub/desimodel#48, desihub/desimodel#49) .  In the meantime, you can look at and further edit the files on the `desimodel-update` branch.
