### ISSUE TITLE
Is mockobserving going to be merged?

### ISSUE THREAD

**Issue by weaverba137** [desihub/desidatamodel#62]
Is the mockobserving branch still required?

**Comment by sbailey** [comment]
We still need this as a reference for what we are trying to achieve with the data model updates, though the work on the ground has already gotten ahead of this.  As part of the 18.9 release, we should make another datamodel update that might borrow pieces of this branch as a starting point, and then we can close this.

**Comment by sbailey** [comment]
I'll remove that branch now that that 18.11 datamodel has been updated.
