### ISSUE TITLE
update datamodel for software release 18.11

### ISSUE THREAD

**Issue by sbailey** [desihub/desidatamodel#64]
Update the data model for software release 18.11 based on files in /project/projectdirs//desi/datachallenge/reference_runs/18.11/

Lots of formats changed, in particular
* target catalogs
* fiber assign output
* FIBERMAP HDU of fibermap, frame, cframe, and spectra files

**Comment by sbailey** [comment]
The mockobserving branch may have useful text to re-use since it was the prototype format for the updates to target selection, fiberassign, and fibermap, but don't just directly merge from that branch.  After the datamodel has been updated for 18.11, that branch can be closed.

**Comment by weaverba137** [comment]
The latest targets.fits files have an array-valued column called DCHISQ with size 5.  Does the number 5 have any significance like in SDSS (*ugriz*)?

**Comment by geordie666** [comment]
The 5 columns correspond to successive morphological fits by Tractor. DCHISQ is described on the Legacy Surveys website as follows:

"Difference in χ² between successively more-complex model fits: PSF, REX, DEV, EXP, COMP. The difference is versus no source."

**Comment by weaverba137** [comment]
@geordie666, good, that means I can give the expanded database columns meaningful names.
