### ISSUE TITLE
Add desisurvey files to datamodel

### ISSUE THREAD

**Issue by dkirkby** [desihub/desidatamodel#65]
The files owned by desisurvey that probably need documented data models are:

Ephemerides written by desisurvey.ephem.Ephemerides
Design HAs written by desisurvey.scripts.surveyinit.calculate_initial_plan
Afternoon planning state written by desisurvey.plan.Planner.save
Tile scheduler state written by desisurvey.scheduler.Scheduler.save

(copied from desihub/desisurvey#91)

**Comment by sbailey** [comment]
I have added data model stubs for these files in the doc/DESISURVEY_OUTPUT/ directory of the desisurvey branch of this repo.  @dkirkby please fill in the descriptions.

**Comment by sbailey** [comment]
Added in PR #70
