### ISSUE TITLE
Add surveysim files to datamodel

### ISSUE THREAD

**Issue by dkirkby** [desihub/desidatamodel#66]
The files owned by surveysim that probably need documented data models are:

Survey per-tile and per-night statistics written by surveysim.stats.SurveyStatistics.save
Simulated exposure metadata written bysurveysim.exposures.ExposureList.save

(copied from desihub/surveysim#60)

**Comment by sbailey** [comment]
I have added data model stubs for these files in the doc/DESISURVEY_OUTPUT/ directory of the desisurvey branch of this repo.  @dkirkby please fill in the descriptions.

**Comment by sbailey** [comment]
Stubs for these were added in PR #70, but the table columns don't have comments defining them yet.  Leaving this ticket open for now.

**Comment by sbailey** [comment]
Details added in PR #71.  Thanks @dkirkby.  Closing.
