### ISSUE TITLE
HDU 0 EXTNAME policy

### ISSUE THREAD

**Issue by sbailey** [desihub/desidatamodel#69]
DESI FITS files EXTNAME requirements:
* FITS extensions *shall* have an EXTNAME set
* Pipeline code *shall* access FITS extensions by name not by number
* User code *should* access FITS extensions by name not by number

i.e. we reserve the right to re-order or insert HDUs; accessing them by name won't break but accessing them by number might.

For discussion: a potential special case is blank HDU 0, where the "real" data are in HDU 1 (with an EXTNAME!) because they are a binary table that the FITS standard doesn't allow in HDU 0, e.g. the targets catalog.  In formal FITS nomenclature I don't even think that HDU 0 is an "extension" but the standard doesn't forbid giving it an EXTNAME anyway (thankfully).  I suggest our HDU 0 EXTNAME policy should be:

  1. if HDU 0 has blank data and no non-standard header keywords, it *should not* have an EXTNAME
  2. if HDU 0 has blank data but meaningful header keywords, HDU 0 *should* have EXTNAME=PRIMARY (Note: *should* not *shall*)
  3. if HDU 0 has meaningful data, it *shall* have an EXTNAME set that *should* be something more meaningful than "PRIMARY"

I suggest that `check_model` and unit tests check (3) (the only "*shall*") and do a best-effort basis on (1) and (2), but if that gets too irritating or there are messy corner cases, don't worry about it.

Comments in PR #68 have a list of known files with HDU 0 that have no EXTNAME.

**Comment by weaverba137** [comment]
I endorse this policy.  I don't think it would be too hard to update the `check_model` code to enforce this.

**Comment by dkirkby** [comment]
What is the best practice for a FITS file containing a single binary table?

**Comment by sbailey** [comment]
@dkirkby for the case of a single binary table:
* HDU 1 *shall* contain a meaningful EXTNAME.
* If HDU 0 has blank data and no non-standard keywords (i.e. it can be completely ignored), then HDU 0 *should not* have an EXTNAME.
* If HDU 0 has useful keywords that the user would be expected to read and use, then it *should* have EXTNAME = PRIMARY (and for convenience, consider putting those keywords into the named HDU 1 instead or in addition so that they can just read the header+keyword from the single named HDU).

**Comment by dkirkby** [comment]
Ok, thanks for the clarification. Since the astropy `Table.write()` is not flexible enough to support this I am using:
```
hdus = astropy.io.fits.HDUList(astropy.io.fits.PrimaryHDU())
hdus.append(astropy.io.fits.table_to_hdu(table))
hdus[-1].name = 'EXTNAME'
hdus.writeto(filename, overwrite=True)
```

**Comment by sbailey** [comment]
If you were using `Table.write()` I think that would be my second bullet: HDU 0 is blank with no non-standard keywords and could be ignored and should not have an EXTNAME, while still wanting an EXTNAME for HDU 1.  You can get an EXTNAME into HDU 1 with:
```
# data is an astropy.table.Table object
data.meta['EXTNAME'] = 'SOME_MEANINGFUL_NAME'
data.write(filename, overwrite=True)
```
