### ISSUE TITLE
tool to check if data model is current

### ISSUE THREAD

**Issue by sbailey** [desihub/desidatamodel#7]
We originally dreamed of having the desidatamodel formats be both human and machine readable such that code could verify if the datamodel files were correct.  We found it hard to make something that was human-friendly while also being strict and complete enough for computer parsing.  And in the meantime our datamodel has gotten out of sync with our data files.  I suggest a pragmatic middle ground:

Write a script to run on a production directory and verify that:
  * every fits file has a corresponding datamodel file
    * in the future this could be expanded to hdf5, yaml, etc. too
  * every HDU in the fits file has a description in the datamodel file (based on EXTNAME)
  * for binary tables, confirm that the columns in the file match the columns in the datamodel

Print a brief report for discrepancies, e.g.
```
blat/foo/bar/quat.fits missing from datamodel
blat/foo/bar/quiz.fits datamodel missing description of HDU EXTNAME=BIZBAT
```

Once a file of type X has been checked, all other files of that type could be skipped — i.e. we don't need to verify 300000 frame files all have the same format.  I think all of our files have the form `directory/prefix-*.*` — i.e. you can parse and key off of "prefix" since we don't reuse the same prefix for different kinds of files in different locations.

Even keeping the files and datamodel in sync at that level would be very useful.  Checking header keywords, float32 vs. float64, etc. could come later.

The interface might look something like
```
checkmodel /project/projectdirs/desi/spectro/redux/dc3 --root DESI_SPECTRO_REDUX/PRODNAME
checkmodel /project/projectdirs/desi/target --root DESI_TARGET
```

I hope this is viable.  Actually trying to implement it could reveal any gotchas.

**Comment by weaverba137** [comment]
This doesn't seem too hard, but who gets the "blame" when discrepancies are detected?

- Obviously, if a file does not have a data model, the data model needs to be fixed.  But what if *no* files are present where the data model says they should be?  For example, let's say that we create a data model for guider files, but then don't bother to simulate them, so that no real guider files can be found.  Who's at fault then?
- If there is a discrepancy in terms of number/name of HDUs, does that mean the data model is wrong or that someone has "snuck in" unapproved HDUs, or just misspelled an EXTNAME?
- Similarly for table columns.

**Comment by sbailey** [comment]
File in datamodel but not in directory structure: for the purposes of this tool, ignore.  Or maybe print single "datamodel file blat/foo/bar/glum.fits missing from directories" message.  The main point of this tool is to check that the datamodel is current for the files that are being written.  I'm ok if the other way around isn't supported (at least not yet).

Discrepancies in HDUs or columns: the tool just reports discrepancies and the human running the tool can decide what action to take.  In our current state of affairs, it is usually the datamodel that needs to be updated.

e.g. right now I'm trying to wrap up a spectro pipeline release, and it is a pain to manually check consistency between the datamodel and the actual files.

**Comment by weaverba137** [comment]
@sbailey, you asked that dc3 be used as the initial validation sample for comparing data to the model. I can't find any files in desi/datachallenge/dc3.  Are they on scratch somewhere?

**Comment by sbailey** [comment]
They are in /project/projectdirs/desi/spectro/redux/dc3c/ or temporarily on scratch in /scratch1/scratchdirs/sjbailey/desi/spectro/redux/dc3c/ .

For the record, [DESI-1950](https://desi.lbl.gov/DocDB/cgi-bin/private/ShowDocument?docid=1950) documents the file locations, code versions used, performance results, etc.

**Comment by weaverba137** [comment]
Ah, I see it now.  Also, is PRODNAME now officially called SPECPROD?  The data model still has the former.

**Comment by tskisner** [comment]
That is desispec issue #127.  I was going to change it, but not until 
the end of the current round of pipeline refactor (to minimize the 
frequency when things break).

-T
