### ISSUE TITLE
Compare by key, not by list.

### ISSUE THREAD

**Issue by weaverba137** [desihub/desidatamodel#74]
* Compare HDUs by EXTNAME, not by order in the FITS or model file.
* Compare HDU keywords by keyword, not by order.
* Compare Column names by Column name?  Can we at least specify the order of columns in a table?
* This may also make it easier to support required and optional keywords.

**Comment by sbailey** [comment]
Let's also compare columns by name not by order.

**Comment by weaverba137** [comment]
Reviving this old ticket as part of everest analysis.

* *Done*: Compare HDUs by `EXTNAME`, not by order in the FITS or model file.
  - Although example data files are analyzed in the order of the real HDUs in the real data file, the corresponding data model can have any HDU ordering in principle and is keyed by `EXTNAME`.
* *Done*: Compare HDU keywords by keyword, not by order.
  - Keyword lists are converted to sets which have no intrinsic ordering.
  - Missing or extraneous keywords are still identified.
* **TO DO**: Compare Column names by Column name.
* **TO DO**: Exact specification for optional HDUs, Keywords and Columns.

**Comment by weaverba137** [comment]
Compare column names by Column name is now implemented, although some unit tests should be added.

**Comment by weaverba137** [comment]
Closing this ticket in favor of #86.
