### ISSUE TITLE
Quicklook to Nightwatch

### ISSUE THREAD

**Issue by weaverba137** [desihub/desidatamodel#77]
How similar are Nightwatch outputs to Quicklook?  That is, could we get away with renaming the current Quicklook directory and tweaking some of the files?  Also, does this transition make #49 moot?

**Comment by sbailey** [comment]
The nightwatch outputs are quite different from quicklook (though when we do get the point of documenting nightwatch, the `doc/DESI_SPECTRO_REDUX/SPECPROD/exposures/` directory will be a good starting point.  And yes, #49 is now moot; I just closed it.

**Comment by weaverba137** [comment]
OK.  Should we remove the existing quicklook directory then?

**Comment by weaverba137** [comment]
@sbailey , is it OK to remove quicklook entirely as part of the 19.9 updates?

**Comment by sbailey** [comment]
Yes

**Comment by weaverba137** [comment]
Thank you.  Removed in 32b1e4a.
