### ISSUE TITLE
data model issues to check

### ISSUE THREAD

**Issue by sbailey** [desihub/desidatamodel#80]
This is a meta ticket to capture a list of questions leftover from PR #78.

## DESISURVEY_OUTPUT

* No model file for `exposures.fits`, `test-tiles.fits`.

## DESI_SPECTRO_DATA

* The datachallenge files are not a useful comparison to the model.
* See also comments on fibermap files below.

## DESI_SPECTRO_REDUX

* Many files types are not generated by the datachallenge.
* I'm very worried that passing around huge fibermap/target tables is going to
  result in lots of inconsistencies between files as columns are added or
  removed.

## DESI_SPECTRO_SIM

* No comparison possible for `pix` and `simpix` files.
* Only routine header keyword and column name cleanup are needed.
* Fibermap files no longer have HDU2, `TARGETS`.
* Simspec `TRUTH` table no longer has `CONTAM_TARGET`.
* Why are `NUMOBS_INIT` and `PRIORITY_INIT` `int64`, when `NUMOBS_MORE` is `int32`.
  And in any case, why are we planning for `2**32` or `2**64` exposures?
* There are a number of type changes in simspec, and some columns
  that used to have units no longer do.  See the `OBSCONDITIONS` table especially.

## DESI_TARGET

* Is there any way to more accurately represent the "official" pipeline layout?
  For example, is the position of fiberassign under DESI_TARGET reflective of
  actual operations?
* The fiberassign data model file is named `tile-TILEID-FIELDNUM.rst` but the files
  are named `tile-TILEID.fits`.
* What happened to the standards files?
* Why did `skies.rst` get named that?  It's called `sky.fits`.
  Are these really meant to be the same?  There are a lot of changes.
* mtl files have no units on any column.  Some of those columns *have* to have units.
  In fact, units are missing from basically every `DESI_TARGET` file.
* mtl files have `NUMOBS_INIT` as `int64`, but it is `int32` in other files.
* targets file do not contain `PRIORITY`?
* There are several minor differences among truth, sky, mtl that should be
  checked in detail.
* Why are `ALLMASK_[GRZ]` columns `float32`?  The description is pretty clear
  that it should be an integer.
* `SEED` keyword in truth table looks dubious.  Why not an integer with a comment?
* Layout of tile file `FIBERASSIGN` table is radically different from other
  files.
* Does *every* HDU in `tile` have to have the same keywords?

**Comment by geordie666** [comment]
Related to this issue:

The `DESI_TARGET` files for actual data do not reflect the layout in the mocks/minitest reference runs. For instance, the `DESI_TARGET` files have a `resolve`, and can be for SV (*e.g.*`sv1`) or the Main Survey (`main`). We need to either align the mocks and real targets or have separate data models.

Either way, the `DESI_TARGET` data model should be updated so that the directory path for the target files is encoded in the actual path in `desidatamodel`.

**Comment by moustakas** [comment]
I would like to keep *trying* to keep the mocks aligned with the data. My tentative plan was to do a big reassessment/realign of the output of `select_mock_targets` after DR9 is in-hand; it definitely has a lot of catching up to do!

**Comment by weaverba137** [comment]
@sbailey, per our conversation about data model issues last week, is there anything in this ticket we can make progress on, or maybe is now irrelevant?

**Comment by sbailey** [comment]
@weaverba137 from quick scan, many/most of these are still relevant, but we should focus our efforts on updating the data model that describes the actual observed data rather than the sims, e.g. starting with denali.  A few items:
  * the spectra / coadds / zbest / redrock files have a completely different directory structure under `tiles/` instead of `spectra-64`.
  * fiberassign output is now `fiberassign-TILEID.fits.gz` instead of `tile-TILEID-FIELDNUM.fits` and has many updates to the forma
  * the FIBERMAP HDUs inherit from fiberassign files and thus also are changed
  * review SCORES table
  * would be helpful to have high-level summary of mask bits either defining them, or providing the links to all the places where they are defined.

**Comment by weaverba137** [comment]
Thanx @sbailey.  I'm going to repurpose this issue to focus on denali then.  Could you remind me though, is the move to a `tiles/` directory permanent?  That is, we will never again use `spectra-64/`?  Or should we continue to document both?

I feel like high-level summaries of the mask bits belongs in the package that contains the bits, because otherwise you have to modify at least two packages every time one of the bits is changed.  This is related to desihub/desiutil#113.

**Comment by sbailey** [comment]
`tiles/` is permanent, and `spectra-64/` will be replaced with a reorganized structure under a `healpix` name, but that reorganized version doesn't exist yet.  In the main survey (and svda) we will have both.

**Comment by weaverba137** [comment]
This PR reflects an "audit" from 2019 and should be superseded by tickets that reflect the current state of the real data.  For example, #94 and other, closed tickets that updated the redux data.
