### ISSUE TITLE
Milky Way Survey outputs datamodel

### ISSUE THREAD

**Issue by segasai** [desihub/desidatamodel#82]
Hi, 

We have currently the working version of the datamodel for some parts of the MWS output https://github.com/segasai/desidatamodel/tree/mwbranch
Currently I put our output files in DESI_SPECTRO_REDUX/SPECPROD/spectra-NSIDE/PIXGROUP/PIXNUM/
But presumably we want to place them in some other folder like 
DESI_MWS_REDUX . 
What would be the steps necessary to start merging our branch with the main desidatamodel ?
At least all the travis tests are passing.  (I also assume that we *do* want our datamodel merged).

   Sergey

Also CC to @callendeprieto

**Comment by weaverba137** [comment]
It depends on how these files are generated.  Are these directly produced by the main spectroscopic pipeline, by an "afterburner" stage, or are they generated with an entirely separate process?

**Comment by segasai** [comment]
1) They are produced on NERSC.
2) They are produced not by the main pipeline but by https://github.com/segasai/rvspecfit and https://github.com/callendeprieto/piferre which are two main codes of the MWS pipeline
3) I don't know if the codes can be called afterburner, or not, but currently me/Carlos run the jobs manually given the list of spectra files, but we have already a code developed (by Mei-Yu Wang) that does the machinery of submitting the jobs automatically on new data and running both of the MWS codes. 
Here is the example location/structure of our output on nersc:
/global/cfs/cdirs/desi/science/mws/data/minisv2/rv_output/20200304/00053128/rvmod-64-00053128.fits

**Comment by weaverba137** [comment]
@sbailey, do you have any preference on this?  My suggestion would be `DESI_SCIENCE_MWS`.  I'd also recommend changing `data/minisv2` to `redux/minisv2`, since 'data' is usually reserved for 'raw data'.  Then your path would be something like `DESI_SCIENCE_MWS/SPECPROD/rv_output`.

**Comment by segasai** [comment]
Sure, regarding data vs redux folder naming.
Also we will have  the sp_output/ which is the output of the stellar parameters pipeline from @callendeprieto . Presumably we'll just place its outputs in DESI_SCIENCE_MWS/SPECPROD/sp_output then (we don't have yet the properly formatted datamodel files for that, but it is currently very similar to rv_output files )

**Comment by sbailey** [comment]
I'm ok with either `DESI_SCIENCE_MWS` or `DESI_MWS_REDUX`, though I do sort of like the "REDUX" version for symmetry with `DESI_SPECTRO_REDUX`, perhaps implying some aspiration toward pipelining formality, tags, releases, etc. and not just a dumping ground for stuff from the working group.

Either way, let's pick something that we'd be happy with using for other working groups that want to have their own codes contributing to official output data products of eventual Data Assemblies.  e.g. `DESI_SCIENCE_LYA/BGS/C3/QGC` or `DESI_LYA/BGS/C3/QGC_REDUX`

@segasai consider adding an additional directory layer defining the version of your pipeline that was used in addition to the `SPECPROD` that was used as input.  e.g. for the SV data assembly (perhaps named "svda"), you may end up running multiple versions of your pipeline(s) for comparison, but the current structure only has one output directory per specprod input.

**Comment by segasai** [comment]
Thanks for the suggestions, Steven. We already have sort of way of indicating of different pipeline versions/runs, although currently those are 'blended' with the specification of dataset we are processing. Like here
data/minisv2_tiles/rv_output/63075//20200219/rvtab-0-63075-20200219.fits 
data/minisv2_tiles_200327/rv_output/63075//20200219/rvtab-0-63075-20200219.fits
(for the two processed versions of the same data). I can see separating that.
Also regarding pipelining formality, in all the currently RVS processed files I am storing all the information about versions of the software, versions of input files etc, like below
DEPNAM03= 'rvspecfit'          / Software                                       
DEPVER03= '0.0.4.200429dev35c2c5' / Version                                     
DEPVER06= '5.1.1   '           / Version                                         
TMPLCON0= 'desi_b  '           / Spec arm config name                           
TMPLREV0= 'v200429 '           / Spec template revision 
I am sure we are not as sophisticated as the main pipeline, but at least we'll know for sure what kind of software version was run.

**Comment by weaverba137** [comment]
@sbailey , is any action by the Data Management team needed on this?  For example, do we need to define additional environment variables in desitree, or is that left to the MWS team to do that in their own code or module files.

**Comment by weaverba137** [comment]
@segasai, @sbailey, this issue appears to have been dormant for a year.  Is this needed for SVDA?  If so, @segasai, when can we expect a pull request?

**Comment by weaverba137** [comment]
@segasai this issue has been dormant for almost 18 months now.  When can we expect a pull request?

**Comment by weaverba137** [comment]
@callendeprieto, @segasai recently suggested that you should take over this issue. Quote:

> We didn't have the datamodel from the second MWS pipeline in. My current understanding is that the MWS products will be kind'a value added/additional catalogs as opposed to be part of the main SVDA. I think @callendeprieto knows more about this, because I think he is part of the SVDA team.

While this issue is not urgent, I don't want it to fall off the radar either.

**Comment by weaverba137** [comment]
@callendeprieto, @segasai, since the MWS data model is now at https://desi-mws-edr-datamodel.readthedocs.io/en/latest/, I don't think this issue needs to remain open.
