### ISSUE TITLE
fitsverify errors and warnings on pipeline output

### ISSUE THREAD

**Issue by weaverba137** [desihub/desidatamodel#87]
Targeting everest first, make sure that all file types give no warnings from `fitsverify`.

**Comment by weaverba137** [comment]
@sbailey, while working on this, I notice there are lots of `~` files floating around, for example `*.csv~` files in `processing_tables/` or `*.slurm~` files in `run/`.  Can we narrow down which top-level directories and which file types with never be archival?

**Comment by sbailey** [comment]
Everything under desi/spectro/redux/everest is supposed to be archival.  That being said, you've obviously found some editing leftovers from editing files by hand for error recovery, and we should cleanup files like that from Fuji before its final release.

For the purposes of this ticket, run fitsverify on every kind of fits file you can find and ignore these non-fits files.  Please help us remember during Fuji vetting to search for non-archival cases like `*.*~` and remove those before freezing.  The pipeline itself does not purposefully create `*.*~` files.

In case you trip on them, see #1397 for another case of calibnight/YEARMMDD/tmp/fiberflatnight-camera-*-lamp-?.fits temporary files that the pipeline should automatically remove but didn't.  Although those will disappear for Fuji, if they don't pass fitsverify we'd probably want to know...

**Comment by weaverba137** [comment]
Thank you that is helpful.  I am building up the list of all possible FITS files and did notice the tmp/ directories.

What about cases where there is code embedded in the run directory?  Is that a feature or should that code be checked into a repository?

**Comment by weaverba137** [comment]
And there's `(exposures|preproc}/[0-9]+/old`.  What's that?

**Comment by sbailey** [comment]
Thanks for your checks.  We do put code under the run/scripts/ directory when we need to do a one-off task for a specific production and that task isn't already captured in the tagged code used for the production.  Those scripts often act prototype code that is then generalized and committed to desispec for future productions.  In some sense, they are like the batch bash scripts as a record of what was done, and so should *not* be deleted.

The "old" directories are probably leftovers from some cleanup + rerun where we forgot to delete them, and we should look for cases like that during final Fuji vetting.

**Comment by weaverba137** [comment]
Switching to my other hat: I haven't added it up yet, but do you have the sense of how much the tmp and old directories are contributing to the total volume of everest?  In other words are we archiving stuff at NOIRLab that we really, really don't need?

**Comment by weaverba137** [comment]
* calibnight (tmp): 289 GB
* exposures (old) 120 GB
* preproc (old) 102 GB

So about half a TB.

**Comment by weaverba137** [comment]
@sbailey, in ec3b1c7, you should find a notebook `FitsverifyAll.ipynb` that will run `fitsverify` on a randomly-selected example of every type of file in everest.

Every type of FITS file in everest is matched, except files matched in the `[exclude]` section of the regular expressions.  However it is possible that I've made the list of file types overly specific and that some of them could be combined in a single data model. For example, the several types of `fit-psf` files in `[exposures]`.

Feel free to run this notebook at NERSC.  It uses kernel 21.7e.

**Comment by sbailey** [comment]
Thanks.  Your set of regex appear to be complete, at least to the degree that I can verify without just completely re-implementing what you've already done as a cross check.  i.e. this set looks good.

Adding the cases it highlights in the notebook to this ticket:
```
calibnight fiberflatnight **** Verification found 3 warning(s) and 0 error(s). ****
exposures frame **** Verification found 12 warning(s) and 5 error(s). ****
*** Error:   Keyword #233, SIMPLE is not allowed in extensions.
*** Error:   Keyword #610, EXTEND is not allowed in extensions.
*** Error:   Keyword #235, BSCALE is not allowed in the Bin/ASCII table.
*** Error:   Keyword #234, BZERO is not allowed in the Bin/ASCII table.
*** Error:   Keyword #233, SIMPLE is duplicated or out of order.

exposures fiberflat **** Verification found 6 warning(s) and 4 error(s). ****
*** Error:   Keyword #349, SIMPLE is not allowed in extensions.
*** Error:   Keyword #351, BSCALE is not allowed in the Bin/ASCII table.
*** Error:   Keyword #350, BZERO is not allowed in the Bin/ASCII table.
*** Error:   Keyword #349, SIMPLE is duplicated or out of order.

exposures sky **** Verification found 4 warning(s) and 0 error(s). ****
exposures sframe **** Verification found 10 warning(s) and 5 error(s). ****
*** Error:   Keyword #190, SIMPLE is not allowed in extensions.
*** Error:   Keyword #536, EXTEND is not allowed in extensions.
*** Error:   Keyword #192, BSCALE is not allowed in the Bin/ASCII table.
*** Error:   Keyword #191, BZERO is not allowed in the Bin/ASCII table.
*** Error:   Keyword #190, SIMPLE is duplicated or out of order.

exposures cframe **** Verification found 6 warning(s) and 5 error(s). ****
*** Error:   Keyword #191, SIMPLE is not allowed in extensions.
*** Error:   Keyword #463, EXTEND is not allowed in extensions.
*** Error:   Keyword #193, BSCALE is not allowed in the Bin/ASCII table.
*** Error:   Keyword #192, BZERO is not allowed in the Bin/ASCII table.
*** Error:   Keyword #191, SIMPLE is duplicated or out of order.

exposures fluxcalib **** Verification found 3 warning(s) and 0 error(s). ****
exposures stdstars **** Verification found 6 warning(s) and 4 error(s). ****
*** Error:   Keyword #188, SIMPLE is not allowed in extensions.
*** Error:   Keyword #190, BSCALE is not allowed in the Bin/ASCII table.
*** Error:   Keyword #189, BZERO is not allowed in the Bin/ASCII table.
*** Error:   Keyword #188, SIMPLE is duplicated or out of order.

preproc preproc **** Verification found 8 warning(s) and 5 error(s). ****
*** Error:   Keyword #189, SIMPLE is not allowed in extensions.
*** Error:   Keyword #461, EXTEND is not allowed in extensions.
*** Error:   Keyword #191, BSCALE is not allowed in the Bin/ASCII table.
*** Error:   Keyword #190, BZERO is not allowed in the Bin/ASCII table.
*** Error:   Keyword #189, SIMPLE is duplicated or out of order.

preproc fibermap **** Verification found 7 warning(s) and 5 error(s). ****
*** Error:   Keyword #202, SIMPLE is not allowed in extensions.
*** Error:   Keyword #554, EXTEND is not allowed in extensions.
*** Error:   Keyword #204, BSCALE is not allowed in the Bin/ASCII table.
*** Error:   Keyword #203, BZERO is not allowed in the Bin/ASCII table.
*** Error:   Keyword #202, SIMPLE is duplicated or out of order.
```

For the errors about unallowed keywords, I suspect it is just that we are inheriting keywords from the raw data images and/or multiple input files (raw data + fiberassign...) and they just don't apply downstream and should be stripped.

For the cases that are warnings but no errors, it looks like this code doesn't print the warnings and we'll need to run fitsverify on example files by hand to check what they are, but I suspect that it will be similar issues of (harmless?) keyword propagation from one file to another.

**Comment by weaverba137** [comment]
I've modified the notebook to print out the full `fitsverify` report when any warnings or errors are detected.  Here's a summary by top-level directory and file type.  Note that I'm using 1-based numbering of HDUs to match `fitsverify`.  That is, HDU 1 is the primary HDU.

One interesting thing to note is that even though it is clear that `FIBERMAP` HDUs have a lot of problems, they don't all have the *same* problems, which implies they are being handled in different ways or being injected from different sources by the pipeline.

Even though `fitsverify` considers it a warning, the column names in the stdstars `METADATA` HDU that contain hyphens are serious problem that can cause much pain down the road.

Finally I should highlight that the preproc file examined had a checksum error in one of its HDUs, so that's fairly serious as well.

* calibnight
  - fiberflatnight
    * HDU 1:
      - Warning: Keyword 195, FRAMES has a null value.
      - Warning: Keyword 206, OPENSHUT has a null value.
      - Warning: Keyword 36, EPOCH is deprecated. Use EQUINOX instead.
* exposures
  - frame
    * HDU 1:
      - Warning: Keyword 10, FRAMES has a null value.
      - Warning: Keyword 32, OPENSHUT has a null value.
      - Warning: Keyword 226, NTSSURVY has a null value.
      - Warning: Keyword 43, EPOCH is deprecated. Use EQUINOX instead.
    * HDU 6:
      - Warning: Keyword 208, FRAMES has a null value.
      - Warning: Keyword 220, NTSSURVY has a null value.
      - Warning: Keyword 240, OPENSHUT has a null value.
      - Warning: Keyword 552, DELTARA has a null value.
      - Warning: Keyword 553, DELTADEC has a null value.
      - Warning: Keyword 267, EPOCH is deprecated. Use EQUINOX instead.
      - Warning: The OGIP long string keyword convention is used without the recommended LONGSTRN keyword.  (HEASARC Convention)
      - Error:   Keyword 202, SIMPLE is not allowed in extensions.
      - Error:   Keyword 551, EXTEND is not allowed in extensions.
      - Error:   Keyword 204, BSCALE is not allowed in the Bin/ASCII table.
      - Error:   Keyword 203, BZERO is not allowed in the Bin/ASCII table.
      - Error:   Keyword 202, SIMPLE is duplicated or out of order.
  - fiberflat
    * HDU 1:
      - Warning: Keyword 196, FRAMES has a null value.
      - Warning: Keyword 245, SEEING has a null value.
      - Warning: Keyword 246, TRANSPAR has a null value.
      - Warning: Keyword 37, EPOCH is deprecated. Use EQUINOX instead.
    * HDU 6:
      - Warning: Keyword 353, FRAMES has a null value.
      - Warning: Keyword 402, SEEING has a null value.
      - Warning: Keyword 403, TRANSPAR has a null value.
      - Warning: Keyword 193, EPOCH is deprecated. Use EQUINOX instead.
      - Error:   Keyword 349, SIMPLE is not allowed in extensions.
      - Error:   Keyword 351, BSCALE is not allowed in the Bin/ASCII table.
      - Error:   Keyword 350, BZERO is not allowed in the Bin/ASCII table.
      - Error:   Keyword 349, SIMPLE is duplicated or out of order.
  - sky
    * HDU 1:
      - Warning: Keyword 10, FRAMES has a null value.
      - Warning: Keyword 280, SEEING has a null value.
      - Warning: Keyword 281, TRANSPAR has a null value.
      - Warning: Keyword 43, EPOCH is deprecated. Use EQUINOX instead.
      - Warning: The OGIP long string keyword convention is used without the recommended LONGSTRN keyword.  (HEASARC Convention)
  - sframe
    * HDU 1:
      - Warning: Keyword 42, EPOCH is deprecated. Use EQUINOX instead.
      - Warning: The OGIP long string keyword convention is used without the recommended LONGSTRN keyword.  (HEASARC Convention)
    * HDU 6:
      - Warning: Keyword 462, DELTARA has a null value.
      - Warning: Keyword 463, DELTADEC has a null value.
      - Warning: Keyword 248, EPOCH is deprecated. Use EQUINOX instead.
      - Warning: The OGIP long string keyword convention is used without the recommended LONGSTRN keyword.  (HEASARC Convention)
      - Error:   Keyword 189, SIMPLE is not allowed in extensions.
      - Error:   Keyword 460, EXTEND is not allowed in extensions.
      - Error:   Keyword 191, BSCALE is not allowed in the Bin/ASCII table.
      - Error:   Keyword 190, BZERO is not allowed in the Bin/ASCII table.
      - Error:   Keyword 189, SIMPLE is duplicated or out of order.
  - cframe
    * HDU 1:
      - Warning: Keyword 10, FRAMES has a null value.
      - Warning: Keyword 280, SEEING has a null value.
      - Warning: Keyword 281, TRANSPAR has a null value.
      - Warning: Keyword 43, EPOCH is deprecated. Use EQUINOX instead.
      - Warning: The OGIP long string keyword convention is used without the recommended LONGSTRN keyword.  (HEASARC Convention)
    * HDU 6:
      - Warning: Keyword 242, FRAMES has a null value.
      - Warning: Keyword 336, SEEING has a null value.
      - Warning: Keyword 337, TRANSPAR has a null value.
      - Warning: Keyword 614, DELTARA has a null value.
      - Warning: Keyword 615, DELTADEC has a null value.
      - Warning: Keyword 303, EPOCH is deprecated. Use EQUINOX instead.
      - Warning: The OGIP long string keyword convention is used without the recommended LONGSTRN keyword.  (HEASARC Convention)
      - Error:   Keyword 236, SIMPLE is not allowed in extensions.
      - Error:   Keyword 613, EXTEND is not allowed in extensions.
      - Error:   Keyword 238, BSCALE is not allowed in the Bin/ASCII table.
      - Error:   Keyword 237, BZERO is not allowed in the Bin/ASCII table.
      - Error:   Keyword 236, SIMPLE is duplicated or out of order.
  - fluxcalib
    * HDU 1:
      - Warning: Keyword 10, FRAMES has a null value.
      - Warning: Keyword 32, OPENSHUT has a null value.
      - Warning: Keyword 43, EPOCH is deprecated. Use EQUINOX instead.
  - stdstars
    * HDU 4:
      - Warning: Column 6: Name "DATA_G-R" contains character '-' other than letters, digits, and "_".
      - Warning: Column 7: Name "MODEL_G-R" contains character '-' other than letters, digits, and "_".
    * HDU 6:
      - Warning: Keyword 183, FRAMES has a null value.
      - Warning: Keyword 214, OPENSHUT has a null value.
      - Warning: Keyword 521, DELTARA has a null value.
      - Warning: Keyword 522, DELTADEC has a null value.
      - Warning: Keyword 241, EPOCH is deprecated. Use EQUINOX instead.
      - Error:   Keyword 177, SIMPLE is not allowed in extensions.
      - Error:   Keyword 520, EXTEND is not allowed in extensions.
      - Error:   Keyword 179, BSCALE is not allowed in the Bin/ASCII table.
      - Error:   Keyword 178, BZERO is not allowed in the Bin/ASCII table.
      - Error:   Keyword 177, SIMPLE is duplicated or out of order.
* preproc
  - preproc
    * HDU 1:
      - Warning: Keyword 10, FRAMES has a null value.
      - Warning: Keyword 43, EPOCH is deprecated. Use EQUINOX instead.
      - Warning: The OGIP long string keyword convention is used without the recommended LONGSTRN keyword.  (HEASARC Convention)
    * HDU 3:
      - Warning: Data checksum is not consistent with  the DATASUM keyword
      - Warning: HDU checksum is not in agreement with CHECKSUM.
    * HDU 5:
      - Warning: Keyword 222, FRAMES has a null value.
      - Warning: Keyword 569, DELTARA has a null value.
      - Warning: Keyword 570, DELTADEC has a null value.
      - Warning: Keyword 279, EPOCH is deprecated. Use EQUINOX instead.
      - Warning: The OGIP long string keyword convention is used without the recommended LONGSTRN keyword.  (HEASARC Convention)
      - Error:   Keyword 216, SIMPLE is not allowed in extensions.
      - Error:   Keyword 568, EXTEND is not allowed in extensions.
      - Error:   Keyword 218, BSCALE is not allowed in the Bin/ASCII table.
      - Error:   Keyword 217, BZERO is not allowed in the Bin/ASCII table.
      - Error:   Keyword 216, SIMPLE is duplicated or out of order.
  - fibermap
    * HDU 2:
      - Warning: Keyword 199, FRAMES has a null value.
      - Warning: Keyword 230, OPENSHUT has a null value.
      - Warning: Keyword 537, DELTARA has a null value.
      - Warning: Keyword 538, DELTADEC has a null value.
      - Warning: Keyword 257, EPOCH is deprecated. Use EQUINOX instead.
      - Error:   Keyword 193, SIMPLE is not allowed in extensions.
      - Error:   Keyword 536, EXTEND is not allowed in extensions.
      - Error:   Keyword 195, BSCALE is not allowed in the Bin/ASCII table.
      - Error:   Keyword 194, BZERO is not allowed in the Bin/ASCII table.
      - Error:   Keyword 193, SIMPLE is duplicated or out of order.

**Comment by weaverba137** [comment]
Oops, didn't mean to close, just comment.

**Comment by weaverba137** [comment]
Are we also considering raw data files?  Although recent `desi-*.fits.fz` don't show any errors, there are *many* warnings.  The most serious is the warning about column names containing hyphens in the `SPECTCONS` HDU.  Also there are empty header keywords in the `SPEC` HDU.

**Comment by sbailey** [comment]
The warnings about null values in FRAMES, OPENSHUT, DELTARA, DELTADEC, SEEING, TRANSPAR, NTSSURVY trace back to the raw data files which already exist on disk.  We either need to live with that, or we could intercept and "correct" them during preprocessing.  @weaverba137 do you know what the correct way to record a null value in FITS is?

Deprecated EPOCH vs. EQUINOX also traces from the raw data files and I suggest we just live with it or maybe ask Klaus to remove it from future data.  Alternately we could drop it during preprocessing, or maybe even rename it?  Fiberassign files include a column for the REF_EPOCH for proper motion corrections (and in that case, I think it really is *EPOCH*, not *EQUINOX*), and otherwise coordinates are in Gaia-based ICRS which formally no longer uses EQUINOX, but it is very close to J2000.

Hyphens in raw data SPECTCONS column names is something I think we should just live with.  Changing the raw data datamodel would be disruptive.

`DATA_G-R` and `MODEL_G-R` are something that we could change in principle, though they occur only in the stdstar files (i.e. not data products used by non-expert end-users).  Hyphens in columns names is bad practice for anything that might end up in a DB table, but they aren't outright illegal fits and I'd suggest not changing them unless we are fixing a specific problem that we actually have.

**Comment by weaverba137** [comment]
I don't believe FITS supports the concept of null header values.  The best way to proceed would be to determine the types that these header keywords would have if they were not null, and then insert a value of the appropriate type that downstream software can recognize as null.  For example, if `FRAMES` has a string value, use an empty string.  If these are floating point values, `NaN` or `-9999.0` might work.

I disagree that hyphens are something we can just ignore.  First of all there is no guarantee that they could become truly forbidden in the future.  Second, since FITS table columns can be accessed by attribute as well as by key/index, it is dangerous to allow hyphens even without a database.

However, all of that only addresses the *warnings* not the *errors*.  What steps are being taken to address those?

**Comment by sbailey** [comment]
@weaverba137 a new test production is available in $CFS/desi/spectro/redux/f3 , albeit not including healpix based outputs.  Please re-review for urgent datamodel problems.  I'm expecting the header keyword null values to still be there, but most/all of the invalid keywords to be gone (e.g. BZERO in a bintable HDU).

This is an in-progress test production so new nights and files may appear, and some files like the summary zcatalogs, tiles, and exposures tables may get new entries, but I am not anticipating any existing files to disappear or change their structure or keywords.

**Comment by weaverba137** [comment]
## Preliminary results from `f3`:

### Files that have no data model:

* `calibnight/NIGHT/biasnight-CAMERA-NIGHT.fits.gz`
* *e.g.*: `exposures/20210509/00087769/fit-psf-r4-00087769_11.fits`.  Not sure what the `_[0-9][0-9].fits` means.
* *e.g.*: `exposures/20210509/00087799/frame-b4-00087799-no-badcolumn-mask.fits`
* Were the various `blacklisted` files renamed to `listed`?  Were any other changes made to those files that we should be aware of?
* *e.g.*: `tiles/pernight/562/20210511/redrock-tmp-6-562-20210511.fits`.  Need to clean up `tmp` files, presumably.

### Fitsverify errors *other* than header keywords with null values:

* **Most serious**: In several cases the `FIBERMAP` HDU in the files tested had `BZERO` and `BSCALE` in the keywords.  `EPOCH` instead of `EQUINOX` was also present. This suggests that changes to `assemble_fibermap()` are not being applied downstream.  Another clue is that the header keyword comments, which are now very carefully preserved by `assemble_fibermap()` are no longer present.  Example files:
   * `exposures/20210412/00084523/cframe-r0-00084523.fits`
   * `exposures/20210508/00087705/frame-z0-00087705.fits`
   * `exposures/20210506/00087488/fluxcalib-r3-00087488.fits`
   * `exposures/20210507/00087604/sframe-z0-00087604.fits`
   * `exposures/20210508/00087679/fiberflat-b0-00087679.fits`
   * `exposures/20210512/00088157/stdstars-7-00088157.fits`
   * `preproc/20210507/00087562/preproc-b6-00087562.fits`
* *Also serious*: checksum mismatch in (compressed) HDU 2 (zero-indexed). Example file:
   * `preproc/20210507/00087562/preproc-b6-00087562.fits`
* A handful of other files that may not be technically downstream from `assemble_fibermap()` are still using `EPOCH` instead of `EQUINOX`, as well as long strings without the `LONGSTRN`.  These appear in HDU 0, rather than in the `FIBERMAP` HDU and were presumably copied directly from the raw data keywords. Example files:
   * `calibnight/20210511/fiberflatnight-z4-20210511.fits`
* The only file that looks like it actually showed improvement was the fibermap file.  But all that work is not being propagated to the other files.

**Comment by weaverba137** [comment]
* Analyze other `preproc` files in `f3` to see how common the checksum error is.
* Some errors may be coming through `preproc` files, *e.g.* errors in HDU 0. Investigate further.
* Files like `exposures/20210509/00087769/fit-psf-r4-00087769_11.fits` are temporary and can be ignored.
* `biasnight` files do need a data model file.
* At some point Julien needs to more thoroughly document the various `fit-psf` files.

**Comment by sbailey** [comment]
Example command to generate a preproc file for testing:
```
desi_preproc -n 20210412 -e 84523 --cameras r0 \
    --fibermap $DESI_ROOT/spectro/redux/f3/preproc/20210412/00084523/fibermap-00084523.fits \
    --outfile preproc-r0-00084523.fits
```

That is the other major route through which raw data headers propagate into the data stream, so if you can fix that it should significantly help with the downstream files.

**Comment by weaverba137** [comment]
So there are rather a lot of `preproc` files in `f3`, so I sampled about 1% of them, over 100 files. *All* of them had checksum mismatch errors.

**Comment by weaverba137** [comment]
@sbailey, is there a preferred branch of desispec, or version of desimodules I should be using?  Especially if it's the versions you used for `f3`?

**Comment by sbailey** [comment]
f3 was run with the "test-21.12" environment, which might be a moving target, but currently has desispec/0.48.0.  That should be equivalent to master for the purposes of preproc.

It sounds like the checksum mismatches are an unexpected feature of it not stripping out checksums propagated from an upstream files (in most cases we can propagate an upstream header without thinking too much and it will correct things like NAXIS1 to be the correct value for the data, but perhaps that isn't the case for checksums).  This definitely needs to be fixed.

**Comment by weaverba137** [comment]
Confirming that I can reproduce the preproc file errors using the `desi_preproc` command as suggested above.

**Comment by weaverba137** [comment]
This is not directly related to the preproc files, but here's a fun little discovery from `desispec.io.image.write_image()`:
```
    #- Work around fitsio>1.0 writing blank keywords, e.g. on 20191212
```
So maybe these null header keywords are ultimately coming from `fitsio`?

**Comment by weaverba137** [comment]
I think I know what is going on with the invalid checksums: https://github.com/astropy/astropy/issues/4587.

This was fixed a few months ago, and is in astropy 5.0.  However it has not yet appeared in a release of the 4.0.x or 4.3.x series.

**Comment by sbailey** [comment]
For Fuji we will move to astropy 5.0, but still need to verify that preproc checksums are fixed with that.

**Comment by weaverba137** [comment]
Sure, I'll see if I can run a test myself.

**Comment by weaverba137** [comment]
I did a quick test with astropy/5.0 and no other changes to desimodules/test-21.12.  The checksum errors are gone.

**Comment by weaverba137** [comment]
I took a quick look at `preproc-` files in `f5`.  At this point the only errors or warnings are about NULL header keywords.  All other errors and warnings are gone.

**Comment by sbailey** [comment]
from @weaverba137 on Slack:
> After running fitsverify on a randomly chosen sample of every file type in f5, there are only two warnings: header keywords with null values (expected), and complaints about hyphens in column names (stdstars file, also seen before).

Good enough for Fuji, closing ticket.  OK to post additional comments postfacto or open new tickets with specific problems.
