### ISSUE TITLE
Human-readable directories and filenames from everest

### ISSUE THREAD

**Issue by weaverba137** [desihub/desidatamodel#88]
We will likely need to expand the set of human-readable directory and file names.  For reference, these are things like `NIGHT` and `EXPID`, which stand in for harder-to-read regular expressions.  The existing set is [here](https://github.com/desihub/desidatamodel/blob/main/py/desidatamodel/check.py#L32).

It looks like we no longer use `NSIDE` as of everest, but I'm more interested in what to call:

1. `(sv1|sv2|sv3|main)` = `SURVEY`?
2. `(backup|bright|dark|other)` = `CONDITIONS`?
3. `(cumulative|perexp|pernight)` = `TILETYPE`?
4. `[14]x_depth` = `TILETYPE` or does that have such a different data model that it requires a separate section?

To think about this another way, do we need this structure in the data model:
* DESI_SPECTRO_REDUX
  - SPECPROD
    - tiles
      - 1x_depth
        - TILEID
          - SPECTROGRAPH
            - various files...
      - 4x_depth
        - TILEID
          - SPECTROGRAPH...
      - cumulative...
      - perexp...
      - pernight....

or can we get away with this:
* DESI_SPECTRO_REDUX
  - SPECPROD
    - tiles
      - TILETYPE
        - TILEID
          - NIGHT
            - various files....

And similar question for the healpix directory.

**Comment by weaverba137** [comment]
My question above might not apply to the `[14]x_depth` directories because they really are so different.  There is an extra directory level that doesn't fit the other tile directories, & I can't recognize some of the numbers at all.  Here are the regular expressions I identified previously:
```
coadd = tiles/[14]x_depth/[0-9]+/[0-9]/coadd-[0-9]-[0-9]+-[14]xsubset[1-6]\.fits
qso_mgii = tiles/[14]x_depth/[0-9]+/[0-9]/qso_mgii-[0-9]-[0-9]+-[14]xsubset[1-6]\.fits
qso_qn = tiles/[14]x_depth/[0-9]+/[0-9]/qso_qn-[0-9]-[0-9]+-[14]xsubset[1-6]\.fits
redrock = tiles/[14]x_depth/[0-9]+/[0-9]/redrock-[0-9]-[0-9]+-[14]xsubset[1-6]\.fits
spectra = tiles/[14]x_depth/[0-9]+/[0-9]/spectra-[0-9]-[0-9]+-[14]xsubset[1-6]\.fits
```
Is `/[0-9]/` `/SPECTROGRAPH/`?  I have no idea what `[1-6]` means here.

**Comment by schlafly** [comment]
Two cents:

1. (sv1|sv2|sv3|main) = SURVEY?
Yes.
2. (backup|bright|dark|other) = CONDITIONS?
PROGRAM
3. (cumulative|perexp|pernight) = TILETYPE?
I'd suggest COADD or COADDTYPE or INTERVAL.

**Comment by moustakas** [comment]
> 1. (sv1|sv2|sv3|main) = SURVEY?
Yes.
> 2. (backup|bright|dark|other) = CONDITIONS?
PROGRAM
(cumulative|perexp|pernight) = TILETYPE?
> 3. I'd suggest COADD or COADDTYPE or INTERVAL.

For what it's worth, in `fastspecfit` I use `survey`, `program`, and `coadd_type` for these three levels / identifiers.

**Comment by sbailey** [comment]
Another data point: unfortunately "PROGRAM" is overloaded in that it is also a raw data header keyword coming from an ICS GUI field were humans can type arbitrary strings.  I think that is standardized in NTS operations, but the full set of raw data "PROGRAM" values is all over the map.

On the pipeline side, that level of the directory structure is propagated from FAPRGRM in the fiberassign files (with additional corrections for sv1 where that hadn't stabilized yet either).

I'm open to calling this "PROGRAM" in the data model, but we should clarify that this is a more human-readable way of saying "FAPRGRM" and it does *not* mean the PROGRAM that one might find in the raw data files (and thus propagated to other files too).  But that could be quite confusion.  What do others thing?

**Comment by weaverba137** [comment]
OK to go with `PROGRAM`, with some documentation on the exceptions to this (FAPRGRM, sv1, PROGRAM header keyword in raw data).

For `tiles/` structure `GROUPTYPE` / `TILEID` / `GROUPID`.
