### ISSUE TITLE
Update data model for tiles product

### ISSUE THREAD

**Issue by weaverba137** [desihub/desidatamodel#98]
The data model path `DESI_TARGET/fiberassign` is outdated and should be updated:

* The ultimate source for fiberassign files is `DESI_SPECTRO_DATA/NIGHT/EXPID/fiberassign-EXPID.rst`. After those files appear in the raw data, they are checked into the `tiles` product, so the fiberassign data model in that area can refer to the raw data version.
* The equivalent path to the actual data tree is `DESI_TARGET/tiles/TILES_VERSION/TILEXX/fiberassign-TILEID.rst`.  `DESI_TARGET/tiles` is simply a svn checkout of the full `tiles` product.
* There may be other files in the tiles product to document.

**Comment by weaverba137** [comment]
Some header keywords and columns did evolve in commissioning & sv1.  So we can't assume that the files have identical data models.  But it is OK to simply note this potential discrepancy.  Might be better to have the official definition here, and put a link in the raw data.

**Comment by weaverba137** [comment]
@sbailey, who do you recommend for reassignment to get this ready for upcoming data releases?

**Comment by sbailey** [comment]
@araichoor could you help finish the documentation for the fiberassign files in the data model?  Thanks.

**Comment by araichoor** [comment]
sure.

**Comment by araichoor** [comment]
[Replying here to https://github.com/desihub/desidatamodel/pull/103#issuecomment-1130225272]
Please let me know what `fiberassign*rst` file I should update/create.

From your first message in this thread, I understand that `DESI_SPECTRO_DATA/NIGHT/EXPID/fiberassign-EXPID.rst` is the file to edit (and the svn-checkout will then refer to that).
But, as said, I d of course be happy to make any change you d suggest.
So, what file shall I work on?

- a new file `DESI_TARGET/tiles/TILES_VERSION/TILEXX/fiberassign-TILEID.rst` ?
- or rather a new file `DESI_TARGET/fiberassign/tiles/TILES_VERSION/TILEXX/fiberassign-TILEID.rst` be more relevant? as the full path for one of those file is like: `https://data.desi.lbl.gov/desi/target/fiberassign/tiles/trunk/004/fiberassign-004403.fits.gz` (I assume that `TILES_VERSION` is for the `trunk` in the nersc path).

And we should just delete `DESI_TARGET/fiberassign/tile-TILEID-FIELDNUM.rst` ? as this filename (and path) is obselete.

**Comment by sbailey** [comment]
Please work on a new file `DESI_TARGET/fiberassign/tiles/TILES_VERSION/TILEXX/fiberassign-TILEID.rst` and delete the out of date `DESI_TARGET/fiberassign/tile-TILEID-FIELDNUM.rst`.  i.e. make the datamodel match the directory structure and naming of the actual files on disk.  Thanks.

**Comment by weaverba137** [comment]
Closed by #103.
